require File.join(File.dirname(__FILE__), '..', '..', 'lib', 'icuke', 'sdk')

task :install do
  sh "cd sdk4.0 && rake"
end
task :clean do
  sh "cd sdk4.0 && rake clean"
end

task :default => :install
